plugins { id 'com.android.application' }

android {
    namespace 'ma.etafat.vr'
    compileSdk 34

    defaultConfig {
        applicationId 'ma.etafat.vr'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file('../android.keystore')
            storePassword 'etafatvr'
            keyAlias 'android'
            keyPassword 'etafatvr'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
